version: "3.8"

services:
  python-app:
    build: ./python-app
    ports:
      - "8000:8000"
    networks:
      - demo-net

  java-app:
    build: ./java-app
    ports:
      - "9090:9090"
    networks:
      - demo-net

networks:
  demo-net:
    driver: bridge
